### ISSUE TITLE
Fatal error on lxplus9 with nightlies 2024-09-21

### ISSUE THREAD

**Issue by lopezzot** [key4hep/key4hep-spack#651] opened 2024-09-23 12:10 UTC
- OS version: Red Hat Enterprise Linux 9.4 (Plow) 
 - Compiler version: gcc (Spack GCC) 14.2.0

Dear All,

I am experiencing fatal errors using /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh -r 2024-09-21 on lxplus9.  Reproducer:
```sh
git clone git@github.com:lopezzot/DREndcapTube.git
cd DREndcapTube/
source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
mkdir build; cd build
cmake -DCMAKE_INSTALL_PREFIX=../install/ ..
make install
cd ../install/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/lib64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/lib
cd ..
ddsim --steeringFile scripts/steer_e-_10GeV_regexSDAction.py
```
This dumps
```sh
Error in <TInterpreter::AutoParse>: Error parsing payload code for class dd4hep::tools::Evaluator with content:
```
plus a lot of things like
```sh
Error in <TClass::LoadClassInfo>: no interpreter information for class dd4hep::tools::Evaluator is available even though it has a TClass initialization routine.
input_line_45:2:18: error: incomplete type 'dd4hep::tools::Evaluator' named in nested name specifier
 &dd4hep::tools::Evaluator::OK;
```
The same steps but with `source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh -r 2024-09-20` work fine instead.

Any help would be great. Thank you.

**Comment by tmadlener** [comment] 2024-09-23 12:12
There seems to be a general issue with the last nightly build. See also discussions in #650 an #649

**Comment by jmcarcell** [comment] 2024-09-23 13:17
There is something specifically wrong about lxplus, I don't see any of the problems in the build node and CI also seems to pass in other Key4hep repositories.

**Comment by jmcarcell** [comment] 2024-09-23 13:28
A workaround:
```
export LD_LIBRARY_PATH=/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2024-09-21/x86_64-almalinux9-gcc14.2.0-opt/root/6.32.04-vms5ij/lib:$LD_LIBRARY_PATH
```

**Comment by lopezzot** [comment] 2024-09-23 13:35
> A workaround:
> 
> ```shell
> export LD_LIBRARY_PATH=/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2024-09-21/x86_64-almalinux9-gcc14.2.0-opt/root/6.32.04-vms5ij/lib:$LD_LIBRARY_PATH
> ```

Indeed this works. Will it be reverted in new nightlies or should I export root this way from now on?

I think we can close this issue. Thank you.

**Comment by jmcarcell** [comment] 2024-09-24 07:01
It should be fixed today; at least I can not reproduce the issue anymore on lxplus.

**Closed by jmcarcell** 2024-09-24 07:01 UTC
