### ISSUE TITLE
Podio-dump bug 

### ISSUE THREAD

**Issue by JacopoFanini** [key4hep/key4hep-spack#650] opened 2024-09-23 09:45 UTC
Using the latest nightly, I noticed that when I try to use ```podio-dump``` I get the following error:
```
Traceback (most recent call last):
  File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2024-09-21/x86_64-almalinux9-gcc14.2.0-opt/podio/64e87e153e8217375a167123d3567a765935333a_develop-hhsa2x/bin/podio-dump", line 8, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'
```
It seems that ```tabulate``` Python module is missing from the stack

**Comment by tmadlener** [comment] 2024-09-23 09:49
Duplicate of #649

**Comment by jmcarcell** [comment] 2024-09-23 11:11
Let's move the conversation to #649

**Closed by jmcarcell** 2024-09-23 11:11 UTC

**Comment by jmcarcell** [comment] 2024-09-23 11:41
Actually I'm not sure there isn't something else, it's crashing for me if I try to dump the EDM4hep file created by the workflow :thinking:

**Comment by tmadlener** [comment] 2024-09-23 11:59
It seems to be a general issue with the EL9 deployment(?). On Ubuntu 22, I can do this successfully:

```console
$ source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
$ wget https://key4hep.web.cern.ch:443/testFiles/EDM4hep/edm4hep_example_v00-99-01_podio_v01-01.root
$ podio-dump edm4hep_example_v00-99-01_podio_v01-01.root 

input file: edm4hep_example_v00-99-01_podio_v01-01.root
            (written with podio version: 1.1.0)

datamodel model definitions stored in this file: 
 - edm4hep (0.99.1)

Frame categories in this file:
Name      Entries
------  ---------
events          3
################################### events: 0 ####################################
Collections:
Name                                   ValueType                               Size  ID
-------------------------------------  ------------------------------------  ------  --------
CaloHitContributionCollection          edm4hep::CaloHitContribution               1  ced90453
CaloHitMCParticleLinkCollection        edm4hep::CaloHitMCParticleLink             1  085e8cab
CaloHitSimCaloHitLinkCollection        edm4hep::CaloHitSimCaloHitLink             1  7f48d138
CalorimeterHitCollection               edm4hep::CalorimeterHit                    1  6ca8614d
ClusterCollection                      edm4hep::Cluster                           1  55198a8c
ClusterMCParticleLinkCollection        edm4hep::ClusterMCParticleLink             1  54e4fba8
EventHeader                            edm4hep::EventHeader                       1  d793ab91
GeneratorEventParametersCollection     edm4hep::GeneratorEventParameters          1  cdfab090
GeneratorPdfInfoCollection             edm4hep::GeneratorPdfInfo                  1  42e137ca
MCParticleCollection                   edm4hep::MCParticle                        3  f958e466
ParticleIDCollection                   edm4hep::ParticleID                        1  68876508
RawCalorimeterHitCollection            edm4hep::RawCalorimeterHit                 1  4d19395d
RawTimeSeriesCollection                edm4hep::RawTimeSeries                     1  158fe658
RecDqdxCollection                      edm4hep::RecDqdx                           1  a0f4d4b5
RecoMCParticleLinkCollection           edm4hep::RecoMCParticleLink                1  d781c705
ReconstructedParticleCollection        edm4hep::ReconstructedParticle             1  b77a1b60
SimCalorimeterHitCollection            edm4hep::SimCalorimeterHit                 1  b58874cc
SimTrackerHitCollection                edm4hep::SimTrackerHit                     1  a173fdbb
TimeSeriesCollection                   edm4hep::TimeSeries                        1  f66de6e9
TrackCollection                        edm4hep::Track                             1  e73df094
TrackerHit3DCollection                 edm4hep::TrackerHit3D                      1  bd3dabab
TrackerHitPlaneCollection              edm4hep::TrackerHitPlane                   1  64999f5a
TrackerHitSimTrackerHitLinkCollection  edm4hep::TrackerHitSimTrackerHitLink       1  e7fa88c2
TrackMCParticleLinkCollection          edm4hep::TrackMCParticleLink               1  0691ffe5
VertexCollection                       edm4hep::Vertex                            1  61a62fcc
VertexRecoParticleLinkCollection       edm4hep::VertexRecoParticleLink            1  b3cc3908

Parameters:
Name    Type    Elements
------  ------  ----------
```
